# -*- coding: utf-8 -*-
"""ProyectoFinalPredictiva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xENeViTGXWezyjcbiSjgETvzjd8fd9vB

## Predicción Discreta (Clasificación): Arbol de Decisión, Red Neuronal, KNN.
Proyecto Final de Minería de Datos -
Realizado por Blanca Janeth Yepes

### 1. Carga y Decodificación de Datos ARFF
En este primer paso, cargaremos el archivo `.arff` con nuestros datos. Es fundamental decodificar las variables categóricas para que puedan ser procesadas correctamente. También crearemos una copia de seguridad de los datos originales para mantenerlos intactos.
"""

#Importar librerías
import pandas as pd
from scipy.io import arff
import numpy as np

# 1. Cargar los datos desde el archivo .arff: 'ProyectoFinalMineriaEIA2024.arff'
datos_arff, meta = arff.loadarff('/content/ProyectoFinalMineriaEIA2024.arff')
data = pd.DataFrame(datos_arff)

# 2. Decodificar las variables categóricas
# Las variables tipo 'object' suelen ser las categóricas que necesitan decodificación
for columna in data.select_dtypes([object]).columns:
    try:
        data[columna] = data[columna].str.decode('utf-8')
    except AttributeError: # Si ya está decodificado o no es una cadena de bytes
        pass

# 3. Copia de seguridad
data_original = data.copy()
print("Primeras filas de los datos cargados y decodificados:")
display(data.head())
print("Información general de los datos:")
data.info()

"""### 2. Preparación de Datos: Variables Dummies y Codificación de Etiquetas (LabelEncoder)
Para que Scikit-Learn pueda trabajar eficientemente, es imprescindible que todas nuestras variables sean numéricas. En esta sección, aplicaremos `LabelEncoder` exclusivamente a nuestra variable objetivo. Para las variables predictoras categóricas, generaremos 'variables dummies'. Es de suma importancia seleccionar con precisión tanto la variable objetivo como las predictoras categóricas que se transformarán en dummies, ya que esto influirá directamente en el rendimiento de nuestros modelos.
"""

from sklearn.preprocessing import LabelEncoder
import numpy as np

# Reiniciar 'data' a partir de 'data_original' para asegurar un estado limpio
data = data_original.copy()

# --- IMPORTANTE: Aquí configuramos la variable objetivo y las variables categóricas predictoras ---
nombre_objetivo = "EstadoSituacion" # <<< 'EstadoSituacion' es la variable a predecir

# Convertir columnas que deberían ser numéricas a tipo numérico
# Identificación de columnas que son 'object' pero que deberían ser numéricas y podrían contener '?'
potential_numeric_cols = [
    'CapacidaddeVeranoMW', 'CapacidaddeInviernoMW', 'CargaMinimaMW',
    'MesdeOperacion', 'AniodeOperacion',
    'AumentoCapacidadVeranoPlanMW', 'AumentoCapacidadInviernoPlanMW',
    'MesAumentoPlanificado', 'AnioAumentoPlanificado',
    'ReduccionCapacidadVeranoPlanMW', 'ReduccionCapacidadInviernoPlanMW',
    'MesReduccionPlanificada', 'AnioReduccionPlanificada',
    'MesRepotenciacionPlan', 'AnioRepotenciacionPlan',
    'MesOtrasModificaciones', 'AnioOtrasModificaciones'
]

print("Convirtiendo columnas a tipo numérico y manejando '?'...")
for col in potential_numeric_cols:
    if col in data.columns and data[col].dtype == 'object':
        # Reemplazar '?' con NaN y convertir a numérico. Coerce errors para manejar cualquier otro valor no numérico
        data[col] = pd.to_numeric(data[col].replace('?', np.nan), errors='coerce')
        print(f"Columna '{col}' convertida a numérico. Valores no numéricos (incluyendo '?') convertidos a NaN.")

# Rellenar NaNs con la mediana (o media) para columnas numéricas que no son objetivo
for col in potential_numeric_cols:
    if col in data.columns and data[col].isnull().any():
        if col != nombre_objetivo: # No rellenar NaN en la variable objetivo todavía
            data[col] = data[col].fillna(data[col].median()) # Usamos la mediana para ser robustos a outliers
            print(f"NaNs en columna '{col}' rellenados con la mediana.")

print("data.info() después de rellenar NaNs para columnas numéricas:")
data.info()
print("\n")

# Dummies para predictoras con MÁS de 2 categorías (No se borra ninguna)
# Dummies para predictoras con SÓLO 2 categorías (Se borra una)

# Primero, identificar todas las columnas categóricas restantes que no son la variable objetivo
current_object_cols = data.select_dtypes(include=['object']).columns.tolist()
print(f"DEBUG: current_object_cols antes de eliminar el objetivo: {current_object_cols}")

if nombre_objetivo in current_object_cols:
    current_object_cols.remove(nombre_objetivo) # Excluir la variable objetivo
print(f"DEBUG: current_object_cols después de eliminar el objetivo (estas deben ser predictoras): {current_object_cols}")

# Variables que son categóricas y no son la variable objetivo
categorical_predictoras = current_object_cols

if categorical_predictoras:
    print(f"\nSe han identificado las siguientes columnas categóricas para crear dummies: {categorical_predictoras}")
    # Separar en 2 y >2 categorías
    two_category_cols = []
    multi_category_cols = []
    for col in categorical_predictoras:
        if data[col].nunique() == 2:
            two_category_cols.append(col)
        else:
            multi_category_cols.append(col)

    if two_category_cols:
        print(f"Creando dummies para columnas con 2 categorías (drop_first=True): {two_category_cols}")
        data = pd.get_dummies(data, columns=two_category_cols, drop_first=True, dtype=int)

    if multi_category_cols:
        print(f"Creando dummies para columnas con más de 2 categorías (drop_first=False): {multi_category_cols}")
        data = pd.get_dummies(data, columns=multi_category_cols, drop_first=False, dtype=int)
else:
    print("No se encontraron columnas categóricas predictoras para crear dummies.")

print("data.info() después de la creación de dummies (si aplica):")
data.info()
print("\n")

# 3. LabelEncoder EXCLUSIVO para la variable objetivo
if nombre_objetivo not in data.columns:
    raise ValueError(f"La variable objetivo '{nombre_objetivo}' no se encuentra en el DataFrame después de las transformaciones.")

# Manejar '?' o NaN en la variable objetivo antes de LabelEncoder
if data[nombre_objetivo].dtype == 'object' and '?' in data[nombre_objetivo].unique():
    print(f"Eliminando filas con '?' en la variable objetivo '{nombre_objetivo}'.")
    data = data[data[nombre_objetivo] != '?'].copy()
elif data[nombre_objetivo].isnull().any():
    print(f"Eliminando filas con NaN en la variable objetivo '{nombre_objetivo}'.")
    data = data.dropna(subset=[nombre_objetivo]).copy()

print(f"\nAplicando LabelEncoder a la variable objetivo: '{nombre_objetivo}'")
labelencoder = LabelEncoder()
data[nombre_objetivo] = labelencoder.fit_transform(data[nombre_objetivo])

print("\nPrimeras filas de los datos después de dummies y LabelEncoder:")
display(data.head())
print("Clases originales y codificadas de la variable objetivo:")
print(list(zip(labelencoder.classes_, labelencoder.transform(labelencoder.classes_))))
print("\nInformación general de los datos después de preparación:")
data.info()
print("\n")

"""### 3. División, Balanceo y Normalización de los Datos
Aquí, dividiremos nuestro conjunto de datos en dos partes: el 70% para entrenamiento y el 30% restante para prueba, asegurando una división estratificada para mantener la proporción de las clases. Luego, aplicaremos el método SMOTE *solo* al conjunto de entrenamiento para balancear las clases, lo cual es crucial para modelos robustos. Finalmente, normalizaremos las características numéricas, un paso esencial para algoritmos como KNN y las Redes Neuronales, pero mantendremos una copia de los datos sin normalizar para nuestro Árbol de Decisión.
"""

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler

# Asegurar que nombre_objetivo sea el correcto para esta celda
nombre_objetivo = "EstadoSituacion"

# 1. Separar predictoras (X) y objetivo (Y)
X = data.drop(nombre_objetivo, axis=1)
Y = data[nombre_objetivo]

# --- IMPORTANTE:aquí se configuran las variables numéricas para la normalización ---
# Las variables tipo 'int64' o 'float64' que no son dummies suelen ser numéricas.
variables_numericas = X.select_dtypes(include=np.number).columns.tolist() # Identificación automática de numéricas
print(f"Variables numéricas identificadas para normalización: {variables_numericas}")

# 2. División 70/30 estratificada
print("\nDividiendo los datos en conjuntos de entrenamiento (70%) y prueba (30%) de forma estratificada...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, stratify=Y, random_state=42)
print(f"Dimensiones de X_train: {X_train.shape}, Y_train: {Y_train.shape}")
print(f"Dimensiones de X_test: {X_test.shape}, Y_test: {Y_test.shape}")

# 3. Balanceo de datos (Solo al Train)
print("\nBalanceando el conjunto de entrenamiento (SMOTE)...")
smote = SMOTE(random_state=42)
X_train_bal, Y_train_bal = smote.fit_resample(X_train, Y_train)
print(f"Dimensiones de X_train después de balanceo: {X_train_bal.shape}, Y_train después de balanceo: {Y_train_bal.shape}")
print("Distribución de la variable objetivo en Y_train_bal:")
print(pd.Series(Y_train_bal).value_counts())

# 4. Normalización (Solo para KNN, Redes y SVM)
print("\nNormalizando variables numéricas (MinMaxScaler)...")
min_max_scaler = MinMaxScaler()

# Copias para mantener las no normalizadas intactas para el Árbol
X_train_norm = X_train_bal.copy()
X_test_norm = X_test.copy()

if variables_numericas:
    # Fit solo en Train, Transform en Train y Test
    min_max_scaler.fit(X_train_bal[variables_numericas])
    X_train_norm[variables_numericas] = min_max_scaler.transform(X_train_bal[variables_numericas])
    X_test_norm[variables_numericas] = min_max_scaler.transform(X_test[variables_numericas])
    print("Variables numéricas normalizadas.")
else:
    print("No se encontraron variables numéricas para normalizar o la lista 'variables_numericas' está vacía.")

print("\nPrimeras filas de X_train_norm (normalizado):")
display(X_train_norm.head())

"""### 4. Creación y Evaluación de Modelos Individuales
Entrenamiento evaluación individual de los tres modelos de clasificación: el Árbol de Decisión, la Red Neuronal (MLP) y el algoritmo K-Nearest Neighbors (KNN).

#### A. Árbol de Decisión (Entrenamiento sin normalización)
El Árbol de Decisión, por su naturaleza, no exige que los datos estén normalizados. Por ello, lo entrenaremos directamente con los datos balanceados de nuestro conjunto de entrenamiento, sin aplicar ninguna normalización previa.
"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Importar numpy

print("\n--- ENTRENANDO Y EVALUANDO ÁRBOL DE DECISIÓN ---")

# Aprendizaje
# Se usan datos balanceados (X_train_bal), NO normalizados (X_train_bal proviene de X_train_bal.copy() antes de normalizar)
# Se reduce max_depth para acelerar el entrenamiento del ensamble.
model_dt = DecisionTreeClassifier(criterion='gini', min_samples_leaf=2, max_depth=7, random_state=42) # Reducido de 10 a 7
model_dt.fit(X_train_bal, Y_train_bal)

# Predicción y Reporte
Y_pred_dt = model_dt.predict(X_test) # X_test no está normalizado para el árbol
print("\nReporte de Clasificación del Árbol de Decisión:")
print(metrics.classification_report(Y_test, Y_pred_dt, target_names=labelencoder.classes_))

# Visual: Gráfica del Árbol (puede ser muy grande para datasets complejos)
plt.figure(figsize=(25,15))
plot_tree(model_dt, feature_names=X.columns.tolist(), class_names=labelencoder.classes_, rounded=True, filled=True, fontsize=8)
plt.title("Árbol de Decisión")
plt.show()

# Visual: Matriz de Confusión
print("\nMatriz de Confusión del Árbol de Decisión:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_dt), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Matriz de Confusión - Árbol de Decisión")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC del Árbol de Decisión (One-vs-Rest) para cada clase:")

y_score_dt = model_dt.predict_proba(X_test)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_dt[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - Árbol de Decisión (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""#### B. Red Neuronal - MLP (Entrenamiento con datos normalizados)
Dado que las Redes Neuronales son particularmente sensibles a la escala de los datos, es crucial que los entrenemos con conjuntos de datos que hayan sido previamente balanceados y normalizados para asegurar un rendimiento óptimo.
"""

from sklearn.neural_network import MLPClassifier
from sklearn import metrics # Importar metrics
import matplotlib.pyplot as plt # Importar plt
import numpy as np # Importar numpy

print("\n--- ENTRENANDO Y EVALUANDO RED NEURONAL (MLP) ---")

# Aprendizaje:
# Se usan datos balanceados Y normalizados (X_train_norm)
# Se reduce max_iter para acelerar el entrenamiento del ensamble.
model_rn = MLPClassifier(activation="logistic", hidden_layer_sizes=(50,),
                         learning_rate='constant', learning_rate_init=0.02,
                         momentum=0.03, max_iter=100, random_state=3, verbose=False) # Reducido de 500 a 100
model_rn.fit(X_train_norm, Y_train_bal)

# Visual: Curva de Pérdida (Chequeo de sobreentrenamiento)
print("\nCurva de Pérdida de la Red Neuronal:")
plt.figure(figsize=(10, 6))
plt.plot(model_rn.loss_curve_)
plt.title("Curva de Pérdida - Red Neuronal")
plt.xlabel("Épocas")
plt.ylabel("Pérdida")
plt.grid(True)
plt.show()

# Predicción y Reporte
Y_pred_rn = model_rn.predict(X_test_norm) # X_test normalizado para la RN
print("\nReporte de Clasificación de la Red Neuronal:")
print(metrics.classification_report(Y_test, Y_pred_rn, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
print("\nMatriz de Confusión de la Red Neuronal:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_rn), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Greens)
plt.title("Matriz de Confusión - Red Neuronal")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC de la Red Neuronal (One-vs-Rest) para cada clase:")

y_score_rn = model_rn.predict_proba(X_test_norm)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_rn[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - Red Neuronal (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""#### C. K-Nearest Neighbors - KNN (Entrenamiento con datos normalizados)
El algoritmo K-Nearest Neighbors (KNN) se basa en la distancia entre puntos, por lo que la normalización de los datos es un paso fundamental para garantizar su rendimiento óptimo. Por esta razón, entrenaremos nuestro modelo KNN utilizando los datos que han sido previamente balanceados y normalizados.
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np

print("\n--- ENTRENANDO Y EVALUANDO K-NEAREST NEIGHBORS (KNN) ---")

# Aprendizaje
# Se usan datos balanceados Y normalizados (X_train_norm)
model_knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean') # Se pueden ajustar n_neighbors
model_knn.fit(X_train_norm, Y_train_bal)

# Predicción y Reporte
Y_pred_knn = model_knn.predict(X_test_norm) # X_test normalizado para KNN
print("\nReporte de Clasificación de KNN:")
print(metrics.classification_report(Y_test, Y_pred_knn, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
print("\nMatriz de Confusión de KNN:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_knn), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Reds)
plt.title("Matriz de Confusión - KNN")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC de KNN (One-vs-Rest) para cada clase:")

y_score_knn = model_knn.predict_proba(X_test_norm)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_knn[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - KNN (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""#### Curvas ROC Individuales de los Clasificadores Base
Para comprender mejor el desempeño de cada componente de nuestro ensamble, a continuación, presentamos las curvas ROC (Receiver Operating Characteristic) individuales, utilizando la estrategia 'One-vs-Rest'. Estas visualizaciones para el Árbol de Decisión, KNN y la Red Neuronal nos permitirán analizar cómo cada modelo maneja la clasificación de las distintas clases de forma aislada.
"""

import matplotlib.pyplot as plt
from sklearn import metrics

print("\n--- GENERANDO CURVAS ROC PARA CADA CLASIFICADOR BASE DEL ENSAMBLE ---")

# Lista de clasificadores base para los cuales queremos las curvas ROC
base_classifiers = [
    ('Árbol de Decisión', model_dt, X_test), # Árbol usa X_test sin normalizar
    ('KNN', model_knn, X_test_norm),       # KNN usa X_test normalizado
    ('Red Neuronal', model_rn, X_test_norm) # RN usa X_test normalizado
]

for name, model, X_test_data in base_classifiers:
    print(f"Generando Curva ROC para: {name}")
    y_score = model.predict_proba(X_test_data)

    plt.figure(figsize=(10, 8))
    for i, class_name in enumerate(labelencoder.classes_):
        y_test_bin = (Y_test == i).astype(int)
        fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score[:, i])
        plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

    plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
    plt.xlabel('Tasa de Falsos Positivos (FPR)')
    plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
    plt.title(f'Curva ROC - {name} (Multiclase One-vs-Rest)')
    plt.legend(loc='lower right')
    plt.grid(True)
    plt.show()

print("\nCurvas ROC para los clasificadores base generadas.")

"""### 6. Ensambles: Votación por Mayoría (Hard) y Votación Ponderada (Soft)
Los métodos de ensamble son una estrategia poderosa para mejorar la capacidad predictiva de nuestros modelos, combinando las decisiones de varios clasificadores base. Exploraremos dos tipos: la Votación por Mayoría (Hard Voting), donde se elige la clase más votada, y la Votación Ponderada (Soft Voting), que asigna pesos a las probabilidades predichas por cada modelo.Este ensamble es el que menos procesamiento utiliza para la base de datos.
"""

from sklearn.ensemble import VotingClassifier

print("\n--- ENSAMBLES: VOTACIÓN HARD Y SOFT ---")

# Agrupamos nuestros clasificadores débiles. Usamos los modelos previamente entrenados.
# NOTA: Para VotingClassifier, los modelos deben tener el método `predict_proba` para 'soft' voting.
# DecisionTreeClassifier y MLPClassifier lo tienen. KNeighborsClassifier también.
clasificadores = [('dt', model_dt), ('knn', model_knn), ('rn', model_rn)]

# --- Votación Hard (Todos pesan lo mismo) ---
# Como KNN y RN exigen datos normalizados, y para ser justos, la votación se ejecutará sobre los datos normalizados.
print("\nEntrenando y evaluando Votación Hard...")
model_vot_hard = VotingClassifier(estimators=clasificadores, voting='hard', n_jobs=-1) # n_jobs=-1 para paralelizar
model_vot_hard.fit(X_train_norm, Y_train_bal)

Y_pred_vot_hard = model_vot_hard.predict(X_test_norm)
print("\nReporte de Clasificación de Votación Hard:")
print(metrics.classification_report(Y_test, Y_pred_vot_hard, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_vot_hard), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Oranges)
plt.title("Matriz de Confusión - Votación Hard")
plt.show()

# Visual: Curva ROC (solo para soft voting o si los clasificadores individuales tienen predict_proba)
# Para 'hard' voting, la curva ROC se calcula de manera diferente o no es directamente aplicable.
# Si quieres la curva ROC, se puede hacer con los modelos individuales o con soft voting.

# --- Votación Soft (Se le asignan pesos a las predicciones de probabilidad) ---
# Pesos sugeridos: 30% Árbol, 40% KNN, 30% RN (Ajustar según desempeño)
print("\nEntrenando y evaluando Votación Soft...")
model_vot_soft = VotingClassifier(estimators=clasificadores, voting='soft', weights=[0.3, 0.4, 0.3], n_jobs=-1)
model_vot_soft.fit(X_train_norm, Y_train_bal)

Y_pred_vot_soft = model_vot_soft.predict(X_test_norm)
print("\nReporte de Clasificación de Votación Soft:")
print(metrics.classification_report(Y_test, Y_pred_vot_soft, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_vot_soft), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.bone)
plt.title("Matriz de Confusión - Votación Soft")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC de Votación Soft (One-vs-Rest) para cada clase:")

y_score_vot_soft = model_vot_soft.predict_proba(X_test_norm)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_vot_soft[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - Votación Soft (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""### 8. Guardando el Modelo Ganador para Despliegue
Una vez que hayamos analizado y comparado el rendimiento de todos nuestros modelos y ensambles, seleccionaremos el 'modelo ganador'. Para maximizar su potencial predictivo, este modelo será re-entrenado con el 100% de los datos disponibles (tanto los de entrenamiento como los de prueba). Es fundamental recordar que, si nuestro modelo ganador requiere datos normalizados (como las Redes Neuronales, KNN o ensambles que los incluyan), nos aseguraremos de utilizar un conjunto `X` completamente normalizado. Finalmente, procederemos a guardar tanto el modelo como los objetos de preprocesamiento esenciales (`LabelEncoder`, `MinMaxScaler`) utilizando la biblioteca `pickle`, preparándolos así para un futuro despliegue en un entorno de producción.
"""

import pickle
import os

print("\n--- GUARDANDO EL MEJOR MODELO PARA DESPLIEGUE ---")

# --- IMPORTANTE: Reemplaza 'model_stack' con tu modelo ganador (ej. model_dt, model_rn, model_knn, model_vot_hard, etc.) ---
modelo_ganador = model_vot_soft # <<< CAMBIADO: Tu modelo ganador ahora es 'model_vot_soft'

# Determinar si el modelo ganador necesita datos normalizados para el re-entrenamiento
# Los modelos que generalmente requieren normalización son KNN, Redes Neuronales y ensambles que los usan.
# El Árbol de Decisión y CatBoost (si se usa con categóricas sin dummies) no lo requieren.
modelo_requiere_normalizacion = isinstance(modelo_ganador, (MLPClassifier, KNeighborsClassifier, VotingClassifier)) # Se quitó StackingClassifier ya que no es el elegido.

print(f"El modelo ganador '{type(modelo_ganador).__name__}' {'REQUIERE' if modelo_requiere_normalizacion else 'NO REQUIERE'} normalización para el re-entrenamiento.")

# 1. Preparar X e Y para el re-entrenamiento con el 100% de los datos
# X e Y ya están definidos al inicio de la preparación de datos (paso 3).

# Si el modelo ganador necesita normalización, normalizamos el 100% de X
if modelo_requiere_normalizacion:
    print("Normalizando el 100% de los datos (X) para el modelo ganador...")
    X_total_norm = X.copy()
    if variables_numericas:
        # Creamos un nuevo scaler o usamos el existente si fue entrenado con los datos correctos
        # Para asegurar, re-entrenamos el scaler con todos los datos numéricos si es necesario
        full_data_min_max_scaler = MinMaxScaler()
        full_data_min_max_scaler.fit(X[variables_numericas])
        X_total_norm[variables_numericas] = full_data_min_max_scaler.transform(X[variables_numericas])
        print("Datos numéricos completamente normalizados.")
    else:
        print("No se encontraron variables numéricas para normalizar en el 100% de los datos.")
    X_para_entrenar_final = X_total_norm
else: # Si el modelo ganador no requiere normalización (ej. Árbol de Decisión)
    print("El modelo ganador no requiere normalización, se usará el 100% de los datos X sin normalizar.")
    X_para_entrenar_final = X

# 2. Re-entrenamos el modelo ganador con el 100% de los datos
print(f"Re-entrenando el modelo '{type(modelo_ganador).__name__}' con el 100% de los datos (X.shape={X_para_entrenar_final.shape}, Y.shape={Y.shape})...")
modelo_ganador.fit(X_para_entrenar_final, Y)
print("¡Modelo ganador re-entrenado exitosamente con el 100% de los datos!")

# 3. Guardar en formato .pkl
filename = 'modelo_clasificacion_final.pkl'
variables_entrenamiento = X.columns.values # Se guardan los nombres de las variables usadas como predictoras

# Exportamos el Modelo, los nombres de variables, el codificador objetivo y el normalizador
# Si el modelo no usa normalización, podemos guardar 'None' o el min_max_scaler original que quizás se usó para comparar.
objs_to_save = [modelo_ganador, variables_entrenamiento, labelencoder]
if modelo_requiere_normalizacion and variables_numericas:
    # Guardamos el scaler entrenado con el 100% de los datos si aplica
    objs_to_save.append(full_data_min_max_scaler)
else:
    objs_to_save.append(None) # Opcional: para mantener la estructura si el scaler no es relevante

with open(filename, 'wb') as archivo:
    pickle.dump(objs_to_save, archivo)

print(f"¡Modelo ganador y objetos relacionados guardados exitosamente en '{filename}'!")