# -*- coding: utf-8 -*-
"""Reglas_de_asociacion_EIA2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xw8uUkztP2GMaCq6JTHc8X3mhh0rms_B

# Reglas de asociación -  Búsqueda de patrones
###Realizado por: Victor Daniel Gil Suarez


* Preparación: num-> cat (Discretización)
* Aprendizaje: apriori
* Evaluación: soporte y confianza
* Interpretación de las reglas
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica
from scipy.io import arff #librería para leer archivos arff

"""# 1. Preparación de datos"""

#Se cargan los datos
meta=arff.loadarff('EIAY2024num.arff') #Cargar los datos en arff
data=pd.DataFrame(meta[0])
data.head() #Muestra los 5 primeros registros

# 2. Decodificar las variables categóricas
# Las variables tipo 'object' suelen ser las categóricas que necesitan decodificación
for columna in data.select_dtypes([object]).columns:
    try:
        data[columna] = data[columna].str.decode('utf-8')
    except AttributeError: # Si ya está decodificado o no es una cadena de bytes
        pass

# 3. Copia de seguridad
data_original = data.copy()
print("Primeras filas de los datos cargados y decodificados:")
display(data.head())
print("Información general de los datos:")
data.info()

from scipy.io import arff
import pandas as pd
from ydata_profiling import ProfileReport

# Leer ARFF
data_arff, meta = arff.loadarff('EIAY2024num.arff')

# Crear DataFrame
data = pd.DataFrame(data_arff)

# Convertir bytes a texto
data = data.applymap(
    lambda x: x.decode('utf-8') if isinstance(x, bytes) else x
)

# Verificar datos
print(data.shape)
print(data.head())

# Crear profiling
profile_data = ProfileReport(data, minimal=True)

profile_data

#Conocemos las variables numéricas
import matplotlib.pyplot as plt

# Histogramas
data.hist(
    figsize=(15,10),   # tamaño más grande
    bins=10
)

# Ajustar espacios automáticamente
plt.tight_layout()

# Mostrar
plt.show()

#Descripción estadística de variables numéricas
data.describe()

data_copia=data.copy()

# Discretización: CapacidaddeVeranoMW

#Se indica la cantidad de rangos
data['CapacidaddeVeranoMW'] = pd.cut(data['CapacidaddeVeranoMW'] , bins=3,labels=['CapacidaddeVeranoMW_baja','CapacidaddeVeranoMW_media','CapacidaddeVeranoMW_alta'])
data['CapacidaddeVeranoMW'].value_counts().plot(kind='bar')

# Discretización: CapacidaddeInviernoMW

#Se indica la cantidad de rangos
data['CapacidaddeInviernoMW'] = pd.cut(data['CapacidaddeInviernoMW'] , bins=3,labels=['CapacidaddeInviernoMW_baja','CapacidaddeInviernoMW_media','CapacidaddeInviernoMW_alta'])
data['CapacidaddeInviernoMW'].value_counts().plot(kind='bar')

# Discretización: CargaMinimaMW

#Se indica la cantidad de rangos
data['CargaMinimaMW'] = pd.cut(data['CargaMinimaMW'] , bins=2,labels=['CargaMinimaMW_baja','CargaMinimaMW_alta'])
data['CargaMinimaMW'].value_counts().plot(kind='bar')

#Discretización: MesdeOperacion
#límites de los rangos: Q1,Q2,Q3 yQ4
data['MesdeOperacion'] = pd.cut(data['MesdeOperacion'] , bins=[0,3,6,9,12],labels=['MesdeOperacion_Q1', 'MesdeOperacion_Q2', 'MesdeOperacion_Q3', 'MesdeOperacion_Q4'])
data.head()

#Discretización: AniodeOperacion
data['AniodeOperacion'] = pd.cut(data['AniodeOperacion'] , bins=3,labels=['AniodeOperacion_sigloI','AniodeOperacion_sigloII','AniodeOperacion_sigloIII'])
data['AniodeOperacion'].value_counts().plot(kind='bar')

data.info()

"""# 2. Aprendizaje

Para el algoritmo apriori todos los datos deben ser categóricos.
"""

#Debemos instalar el paquete para el algoritmo apriori
!pip install -q apyori

print(type(data.iloc[0,0]))

data = data.astype(str)

from apyori import apriori
#precedente->consecuente
#Soporte: frecuencia(precedente,Consecuente)/total_datos
#Confianza: frecuencia(precedente,Consecuente)/datos_precedente
from apyori import apriori

reglas = apriori(
    data.values,
    min_support=0.50,
    min_confidence=0.8
)

reglas = list(reglas)

print(reglas)

"""# 3. Evaluación


*   Soporte
*   Confianza



"""

reglas = pd.DataFrame(reglas)
reglas

"""# **4 Interpretación**

- Regla 50: (Operativa), (capacidadVerano) (CapacidadInvierno) (AñoOperación SigloIII), 0.90

Con el 90% en el sigloIII (1924-2024) las hidroelectricas en temporada de invierno y verano fueron operativas.

- Regla 53: (Operativa), (CargaMinimaBajaMW) (CapacidadInviernoMWBaja) 0.90

Con el 90% a pesar de que fue una temporada de verano, y de proveer una carga minima en MW las hidroelectricas fueron operativas.


Las reglas más interesantes fueron aquellas relacionadas con tecnologías hidroeléctricas, petróleo y energía solar, ya que presentaron valores de lift superiores a 3 y hasta 6.96, indicando asociaciones significativamente mayores a las esperadas por azar. Las reglas basadas en EstadoSituacion=OP fueron menos relevantes debido a sus lifts cercanos a 1, lo que evidencia asociaciones triviales derivadas de la alta frecuencia de dicha categoría en el conjunto de datos.
"""

reglas.to_excel('reglas de asociacion.xlsx')