# -*- coding: utf-8 -*-
"""Taller final clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TRdv8hugqinK9o-5K9skKKeH8xEzI8a

#Taller Final: Clustering
Integrantes: Blanca Janeth Yepes, Victor Daniel Gil y Michel Guevara.

Curso: Estadística Aplicada - Maestría en Ciencia de Datos

# Configuración del Entorno
Montaje de Google Drive: La primera acción realizada consiste en establecer la conexión con Google Drive. Esta operación permite al entorno de ejecución de Colab acceder a los archivos almacenados en la cuenta del usuario, siendo fundamental para la carga del dataset.
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Carga de Librerías Esenciales y base de datos DB:

Se importan diversas librerías de Python, cada una con un rol específico en el flujo de trabajo:

pandas (pd): Gestión y manipulación de estructuras de datos, principalmente DataFrames.
numpy (np): Soporte para operaciones numéricas avanzadas y arreglos de grandes dimensiones.
sklearn.cluster.KMeans: Implementación del algoritmo K-Means para la segmentación de datos.
sklearn.preprocessing.StandardScaler: Herramienta para la estandarización de las características de los datos.
sklearn.metrics.silhouette_score: Métrica para la evaluación de la calidad de los clústeres.
sklearn.impute.SimpleImputer: Utilizado para la gestión de valores faltantes (NaN).
matplotlib.pyplot (plt) y seaborn (sns): Herramientas para la visualización de datos y resultados gráficos.
"""

# Importar librerías necesarias
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.impute import SimpleImputer # Importar SimpleImputer
import matplotlib.pyplot as plt
import seaborn as sns

#  Cargar el dataset
df = pd.read_csv("/content/drive/MyDrive/proyecto final.csv")

"""#Fase 1: Adquisición y Análisis Preliminar de Datos
Carga del Dataset: El archivo proyecto final.csv se carga desde la ubicación especificada en Google Drive, integrándose como un DataFrame de pandas bajo el nombre df. Este DataFrame constituye la base para todo el análisis subsecuente.

Estadísticas Descriptivas de Características Numéricas: Se genera un resumen estadístico exhaustivo para todas las columnas numéricas del DataFrame. Este resumen incluye la cuenta de valores, media, desviación estándar, valores mínimos y máximos, y los cuartiles (25%, 50%, 75%). Esta acción proporciona una visión inicial de la distribución y escala de las variables cuantitativas.

Estadísticas Descriptivas de Características Categóricas: Se identifican y analizan las columnas de tipo categórico (objetos o categorías). Para cada una, se calcula y presenta la frecuencia de aparición de cada valor único, lo cual permite comprender la composición y distribución de las variables cualitativas presentes en el dataset.
"""

# 1.1. Estadísticas descriptivas para columnas numéricas
print("Estadísticas descriptivas para columnas numéricas:")
display(df.describe())

# 1.2 Estadísticas descriptivas para columnas categóricas (frecuencia de valores)
print("\nFrecuencia de valores para columnas categóricas:")
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    print(f"\nColumna: {col}")
    display(df[col].value_counts())

"""#Fase 2: Preprocesamiento de Datos para Clustering
Selección de Características Numéricas: Se crea un subconjunto del DataFrame (X) que incluye exclusivamente las características numéricas. Este paso es imperativo, dado que el algoritmo K-Means opera únicamente sobre datos cuantitativos. Los nombres de estas columnas se conservan para referencia.

Manejo de Valores Ausentes: Los valores nulos (NaN) presentes en las características numéricas de X se imputan utilizando la media de la columna correspondiente. Este proceso es fundamental para evitar errores en algoritmos sensibles a valores faltantes y para preservar la integridad del conjunto de datos.

Normalización de las Características: Se aplica una estandarización a las características numéricas mediante StandardScaler. Este método transforma los datos para que presenten una media de 0 y una desviación estándar de 1, asegurando que todas las características contribuyan equitativamente en los cálculos de distancia inherentes al clustering, eliminando el sesgo por diferencias de escala.
"""

# 2. Seleccionar columnas numéricas
numeric_cols = df.select_dtypes(include=[np.number]).columns
X = df[numeric_cols]

# 2.1. Manejar valores faltantes (NaN) en X
# Imputar los valores faltantes con la media de cada columna
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)
# Convertir de nuevo a DataFrame para mantener los nombres de las columnas
X = pd.DataFrame(X_imputed, columns=X.columns)

#  Normalizar los datos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""#Fase 3: Determinación del Número Óptimo de Clústeres (Método del Codo)
Aplicación y Visualización del Método del Codo: Se implementa el método del codo (Elbow Method) para estimar el número óptimo de clústeres (k). Este procedimiento implica ejecutar el algoritmo K-Means para un rango de valores de k (de 1 a 10) y registrar la inercia (suma de las distancias cuadradas de los puntos a sus centroides) en cada iteración. Posteriormente, se genera un gráfico donde el eje X representa el número de clústeres y el eje Y muestra la inercia correspondiente. El punto de inflexión en la curva ('el codo') sugiere el valor de k que maximiza la cohesión interna de los clústeres sin añadir complejidad innecesaria al modelo.
"""

# 3 Aplicar el método del codo
# Se define un rango de posibles números de clústeres (por ejemplo, de 1 a 10)
max_clusters = 10
sum_of_squared_distances = []

for k in range(1, max_clusters + 1):
    kmeans_model = KMeans(n_clusters=k, random_state=42, n_init='auto')
    kmeans_model.fit(X_scaled)
    sum_of_squared_distances.append(kmeans_model.inertia_)

# 4.1 Visualizar los resultados del método del codo
plt.figure(figsize=(10, 6))
plt.plot(range(1, max_clusters + 1), sum_of_squared_distances, 'bx-')
plt.xlabel('Número de Clústeres (k)')
plt.ylabel('Suma de Distancias Cuadradas (Inercia)')
plt.title('Método del Codo para encontrar el k óptimo')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(range(1, max_clusters + 1))
plt.show()

"""# 3.1 Analisis metodo del codo

Eje X (Número de Clústeres (k)): Representa la cantidad de clústeres que se intentaron formar. En este caso, variamos k desde 1 hasta 10.

Eje Y (Suma de Distancias Cuadradas (Inercia)): Muestra la inercia del modelo K-Means para cada valor de k. La inercia se define como la suma de las distancias al cuadrado de cada punto a su centroide de clúster más cercano. Un valor más bajo de inercia generalmente indica un modelo con clústeres más compactos y mejor cohesionados.

#Fase 4: Implementación y Evaluación del Clustering
Aplicación de K-Means con k=6 Clústeres: Basándose en la interpretación del gráfico del codo, se establece k=6 como el número de clústeres elegido. El algoritmo K-Means se ejecuta con esta configuración, y las etiquetas de clúster resultantes se asignan a una nueva columna ('Cluster') en el DataFrame original df, categorizando cada instancia en uno de los seis grupos.
"""

# 4 Aplicar K-Means con 6 clústeres
kmeans = KMeans(n_clusters=6, random_state=42, n_init='auto') # Añadido n_init para evitar warning
labels = kmeans.fit_predict(X_scaled)
df['Cluster'] = labels

"""# 4.1 Cálculo del Índice de Silueta:
Para evaluar la calidad de la partición obtenida, se calcula el índice de silueta promedio. Este índice mide qué tan similar es un objeto a su propio clúster en comparación con otros clústeres. Un valor de 0.663 indica una buena separación y cohesión de los clústeres.
"""

# 4.1 Calcular el índice de silueta
silhouette_avg = silhouette_score(X_scaled, labels)
print(f"Índice de silueta promedio para 6 clústeres: {silhouette_avg:.3f}")

"""# 4.2 Visualización del Clustering:
 Se genera un gráfico de dispersión bidimensional que representa las dos primeras características numéricas escaladas, coloreando cada punto según su asignación de clúster. Esta visualización facilita la observación de la separación espacial y la estructura de los clústeres.
"""

# 4.2 Visualizar resultados (ejemplo con las dos primeras variables)
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_scaled[:,0], y=X_scaled[:,1], hue=labels, palette="viridis", s=100)
plt.title("Clustering con K-Means (6 clusters)")
plt.xlabel(numeric_cols[0])
plt.ylabel(numeric_cols[1])
plt.show()

"""#Fase 5 Perfilamiento"""

# 5 Calcular las medias de las características numéricas para cada clúster
cluster_centers_df = df.groupby('Cluster')[numeric_cols].mean()

print("Medias de las características numéricas por Clúster:")
display(cluster_centers_df)

# Opcional: Analizar la distribución de características categóricas dentro de cada clúster
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
if not categorical_cols.empty:
    print("\nDistribución de características categóricas por Clúster:")
    for col in categorical_cols:
        print(f"\nColumna: {col}")
        display(pd.crosstab(df['Cluster'], df[col], normalize='index'))

"""#5.1 : Interpretación de los Clústeres
Análisis de Perfilamiento por Clúster: Para comprender la naturaleza de cada clúster, se calculan las medias de todas las características numéricas dentro de cada grupo. Esto crea un 'perfil' cuantitativo para cada clúster, revelando sus propiedades distintivas. Adicionalmente, se analiza la distribución de las características categóricas (Estado y Tecnología) dentro de cada clúster, proporcionando una visión más holística de la composición de cada grupo.

Conclusiones Derivadas: Se establece una conclusión inicial y final, que interpreta las características de cada clúster en relación con un objetivo inferido de 'estado de operatividad'. Se postulan hipótesis sobre la eficiencia operativa basadas en la capacidad y el factor de potencia, destacando la importancia de clústeres de gran capacidad para la red y la potencial optimización en clústeres de alta eficiencia. Se sugiere la integración de datos directos de operatividad y un análisis más profundo de la interacción tecnología-estado-clúster como próximos pasos.

# 5.2 Análisis de Clústeres


Clúster 0 (Capacidad Media-Baja): Este clúster se caracteriza por tener una capacidad de placa, verano e invierno de nivel medio-bajo (alrededor de 17-20 MW). Su factor de potencia es intermedio (~0.87).

Clúster 1 (Capacidad Muy Alta): Este es el clúster con las capacidades más altas, superando los 900-1000 MW en capacidad de placa, verano e invierno. También tiene un factor de potencia relativamente alto (~0.90). Podrían representar instalaciones de gran escala o centrales eléctricas importantes.

Clúster 2 (Capacidad Media-Alta): Con capacidades alrededor de los 170-180 MW, este clúster agrupa instalaciones de un tamaño considerable, pero no tan grandes como las del Clúster 1. Su factor de potencia es similar al Clúster 0 (~0.87).

Clúster 3 (Capacidad Alta): Las instalaciones de este clúster tienen capacidades altas, alrededor de los 480-500 MW, ubicándose entre el Clúster 1 y el Clúster 2 en términos de tamaño. Su factor de potencia es ligeramente superior al promedio (~0.88).

Clúster 4 (Capacidad Baja y Alto Factor de Potencia): Este clúster agrupa instalaciones de baja capacidad (alrededor de 16-17 MW) pero con el factor de potencia más alto de todos los clústeres (~0.98). Esto podría indicar instalaciones muy eficientes o con características específicas de operación.

Clúster 5 (Capacidad Muy Baja y Bajo Factor de Potencia): Este clúster representa las instalaciones más pequeñas, con capacidades de placa, verano e invierno muy bajas (alrededor de 4-5 MW). Además, tienen el factor de potencia más bajo de todos los grupos (~0.79). Esto podría sugerir pequeñas instalaciones o aquellas con menor eficiencia en el uso de la energía.

#Fase 6. Analisis y conclusiones

**Conclusión e interpretación Inicial (Inferida sobre el Estado de Operatividad):**
Nuestros 6 clústeres revelan una segmentación clara de las instalaciones energéticas, principalmente por su capacidad de generación y su factor de potencia. Estos dos factores son clave para inferir el potencial 'estado de operatividad':

**Clústeres de Alta Capacidad (Clúster 1 y 3)**: Representan grandes generadores. Un buen factor de potencia en estos podría indicar una operación estable y eficiente, crucial para la red. Cualquier problema en estos clústeres podría tener un impacto significativo en la operatividad general.

**Clústeres de Baja y Media Capacidad (Clústeres 0, 2, 4 y 5)**: Agrupan instalaciones más pequeñas. Aquí, el factor de potencia se vuelve aún más relevante:
Clúster 4 (Baja Capacidad, Alto Factor de Potencia): Podrían ser instalaciones optimizadas, muy eficientes en su operatividad, lo que sugiere un excelente estado.

**Clúster 5 (Muy Baja Capacidad, Bajo Factor de Potencia)**: Sugiere instalaciones con menor eficiencia o posiblemente con un estado de operatividad más variable o menos óptimo, debido a su menor capacidad y factor de potencia.
"""